plugins:
  - jekyll-remote-theme
remote_theme: zivong/ockham

title: Cyber Safe
tagline: Practice Internet Saftey
description: idk where this goes
author:
  name: shilab
  url: https://github.com/Shilab66
