plugins:
  - jekyll-remote-theme
remote_theme: zivong/ockham

title: [insert name]
tagline: Practice Internet Saftey
description: [insert name]
author:
  name: Shilab
  url: https://github.com/Shilab66
