plugins:
  - jekyll-remote-theme
remote_theme: ariestiyansyah/naringu

title: Cyber Safe
tagline: Practice Internet Saftey
description: Cyber Safe
author:
  name: shilab
  url: https://github.com/Shilab66
